version: "3.7"
services:
    sql:
        image: mcr.microsoft.com/mssql/server
        ports:
            - "1433:1433"
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Tokyo!_Joe1433
        networks: 
            - my-network
    api:
        build:
            context: .
            dockerfile: dev.dockerfile
        ports: 
            - "5000:5000"
        networks:
            - my-network

 
networks: 
    my-network:
        driver: bridge
